# Generated by Django 6.0.3 on 2026-03-14 21:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("message", "0001_initial"),
        ("room", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="room",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="messages", to="room.room"
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="sender",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sent_messages",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="messageattachment",
            name="message",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attachments",
                to="message.message",
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["room", "-created_at"], name="message_mes_room_id_a4a095_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(fields=["room", "id"], name="message_mes_room_id_1b20f4_idx"),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["room", "message_type"], name="message_mes_room_id_1230dd_idx"
            ),
        ),
    ]
