# Generated by Django 6.0.3 on 2026-03-14 21:00

import uuid

import django.contrib.auth.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(blank=True, null=True, verbose_name="last login"),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(blank=True, max_length=150, verbose_name="first name"),
                ),
                (
                    "last_name",
                    models.CharField(blank=True, max_length=150, verbose_name="last name"),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        max_length=32,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Username must be 5–32 characters long, start with a letter, contain only lowercase latin letters, numbers and single underscores, and end with a letter or number.",
                                regex="^[a-z](?:[a-z0-9]|_(?!_)){3,30}[a-z0-9]$",
                            )
                        ],
                    ),
                ),
                ("name", models.CharField(max_length=32)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("avatar", models.ImageField(blank=True, null=True, upload_to="user_avatars/")),
                ("bio", models.TextField(blank=True)),
                ("verified", models.BooleanField(default=True)),
                ("official", models.BooleanField(default=True)),
                ("banned", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "abstract": False,
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="UserBan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "ban_type",
                    models.CharField(
                        choices=[("temporary", "Temporary"), ("permanent", "Permanent")],
                        max_length=16,
                    ),
                ),
                ("reason", models.TextField(blank=True)),
                ("starts_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("ends_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "banned_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="issued_bans",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bans",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("is_profile_public", models.BooleanField(default=True)),
                ("allow_direct_messages", models.BooleanField(default=True)),
                (
                    "who_can_invite_to_room",
                    models.CharField(
                        choices=[
                            ("everyone", "Everyone"),
                            ("friends", "Friends only"),
                            ("nobody", "Nobody"),
                        ],
                        default="everyone",
                        max_length=20,
                    ),
                ),
                (
                    "last_seen_visibility",
                    models.CharField(
                        choices=[
                            ("everyone", "Everyone"),
                            ("friends", "Friends only"),
                            ("nobody", "Nobody"),
                        ],
                        default="everyone",
                        max_length=20,
                    ),
                ),
                ("show_online_status", models.BooleanField(default=True)),
                ("notify_on_direct_message", models.BooleanField(default=True)),
                ("notify_on_room_message", models.BooleanField(default=True)),
                ("notify_on_mentions", models.BooleanField(default=True)),
                ("notify_on_room_invite", models.BooleanField(default=True)),
                ("language", models.CharField(default="en", max_length=8)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="settings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
