# Generated by Django 6.0.3 on 2026-03-14 21:00

import uuid

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("message", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "username",
                    models.CharField(
                        max_length=32,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Username must be 5–32 characters long, start with a letter, contain only lowercase latin letters, numbers and single underscores, and end with a letter or number.",
                                regex="^[a-z](?:[a-z0-9]|_(?!_)){3,30}[a-z0-9]$",
                            )
                        ],
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("avatar", models.ImageField(blank=True, null=True, upload_to="room_avatars/")),
                (
                    "room_type",
                    models.CharField(
                        choices=[
                            ("private", "Private room"),
                            ("group", "Group room"),
                            ("channel", "Channel room"),
                        ],
                        db_index=True,
                        default="private",
                        max_length=20,
                    ),
                ),
                ("is_private", models.BooleanField(default=True)),
                ("is_active", models.BooleanField(default=True)),
                ("participants_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="owned_rooms",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RoomMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("owner", "Owner"), ("admin", "Admin"), ("member", "Member")],
                        default="member",
                        max_length=20,
                    ),
                ),
                ("is_muted", models.BooleanField(default=False)),
                ("is_banned", models.BooleanField(default=False)),
                ("invitation_accepted", models.BooleanField(default=False)),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                (
                    "last_read_message",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="message.message",
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to="room.room",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="room_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="room",
            name="participants",
            field=models.ManyToManyField(
                related_name="rooms", through="room.RoomMember", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.CreateModel(
            name="RoomBan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("reason", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "banned_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="issued_bans_in_room",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bans",
                        to="room.room",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "unique_together": {("room", "user")},
            },
        ),
        migrations.AddIndex(
            model_name="roommember",
            index=models.Index(fields=["room", "user"], name="room_roomme_room_id_dfd299_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="roommember",
            unique_together={("room", "user")},
        ),
        migrations.AddIndex(
            model_name="room",
            index=models.Index(fields=["username"], name="room_room_usernam_176ff8_idx"),
        ),
        migrations.AddIndex(
            model_name="room",
            index=models.Index(fields=["created_at"], name="room_room_created_e9fa4f_idx"),
        ),
    ]
