# Generated by Django 6.0.3 on 2026-03-15 08:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='username',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Username must be 5–32 characters long, start with a letter, contain only lowercase latin letters, numbers and single underscores, and end with a letter or number.', regex='^[a-z](?:[a-z0-9]|_(?!_)){3,30}[a-z0-9]$')]),
        ),
    ]
